plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.flexieecsapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.flexieecsapp"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

//    // Room Database dependencies
//    implementation "androidx.room:room-runtime:2.4.3" // Room Runtime
//    annotationProcessor "androidx.room:room-compiler:2.4.3" // For Java
//    testImplementation "androidx.room:room-testing:2.4.3" // Optional for testing

    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // RecyclerView (for displaying the photos in RecyclerView)
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'

    // LiveData and ViewModel for observing Room data
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.4.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0'
}
